spring:
  application:
    name: SpringBoot-JDBC
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin560
    url: jdbc:mysql://localhost:3306/springboot_db
    username: root
